### ISSUE TITLE
Using github's new Releases feature

### ISSUE THREAD

**Issue by aashah** [ColoradoSchoolOfMines/interface_sdk#20]
I think we should attempt to use the new github feature to upload our binaries: https://github.com/blog/1547-release-your-software

This also creates the potential for using github as our maven 'repo' Maybe you can say a bit more towards that after you've had a chance to look over their blog post Andrew, but I think it'd definitely be a step towards having one location for everything (downloads, code, wiki...etc).

Let me know what you guys think.

**Comment by muff1nman** [comment]
I think this is pretty cool.  However, I am not sure it would be a drop in replacement for what we have considering that besides downloading the interface sdk, the maven repo also holds our third party jars for easy access when building the interface sdk.  

Im gonna try to look into it some more, but it may or may not be what we are looking for.  In addition, is it brand new as of today (6/2/2013)?  Maybe good to let it mature a bit? haha

The other alternative I would like to consider besides migrating the maven repo to another spot (a private Mines server or a Mines sponsored Amazon S3 account) is to use something called Nexus.  Granted I believe this would still involve having another server of a sort, but from what Ive heard from the guys at work is its the goto enterprise solution for what were trying to do. Again, I havent looked into cost or anything but another option none the less.  

Lets keep this issue open until we decide whats the best way to go.  It would be ideal if we could test some of these things. So aakash or anyone else, feel free to try it with our github account.

**Comment by muff1nman** [comment]
This is nifty, but unfortunately doesn't do all that we need to do especially with maven.  We can still upload our binary releases, but then that makes it so that you have to do the tagging from github.  However, what we should be doing is putting in the changelog with the tagged commit.  In the past we have been doing "Version bump" with the actual changelog in the commit before.  So going forward, when making a new release, we should first merge development into master as we have before, but then when we make the following commit to up the version number, we should put the changelog into that commit.  That way the releases on github will show the changelog.

**Comment by muff1nman** [comment]
_Update:_  It looks like we can still go back and upload past binaries.  It would be good to do that, but again its not a replacement for maven.  Therefore Im closing this issue.
