### ISSUE TITLE
Duplicate events after a module lifecycle

### ISSUE THREAD

**Issue by muff1nman** [ColoradoSchoolOfMines/interface_sdk#46]
Brought over from [Pong #13](https://github.com/ColoradoSchoolOfMines/Pong/issues/13).  It seems that the observers are not getting deleted correctly?

**Comment by MattWesemann** [comment]
Yeah, so I called deleteObserver in destroy but then the JVM crashes somewhere in OpenNI. Testing deleteObserver in load (or in the constructor on the non openni2 branch) will work. One idea I am thinking is to totally shut down the Context and restart it. 

Also, the reason StopTrackingAll should not kill event callbacks because you may want to temporarily stop tracking, but then restart (like a user paused a game so want to drop CPU cycles down because you're a friendly developer to the rest of the system).

**Comment by muff1nman** [comment]
Strange.. hopefully the same doesn't happen in Openni 2.  Im in favor of shutting down the context.

**Comment by MattWesemann** [comment]
Just tested it and it works. Will close once when checked in.

**Comment by muff1nman** [comment]
Can you post the commit sha matt?  Im just curious :)

**Comment by MattWesemann** [comment]
I am still testing a couple things (like whether or not to still call stopGeneratingAll, making sure all the gesture stuff gets cleaned up, etc.). Its more that the proof of concept of restarting the context works.

**Comment by muff1nman** [comment]
Ah. gotcha. Test away!  (and shame on me for rushing it haha)

**Comment by MattWesemann** [comment]
Fixed in 06093426cff019f385b6d84a4c0ad0b21e6d964e 
I am still not happy with just closing the context and restarting. Releasing the context actually does very little cleanup work (still have to say stop generating data) and doesn't appear to clean up anything in the generators. Calling dispose on the generators also doesn't do much but hopefully should help leak less memory. One main annoyance is that calling dispose doesn't do any Java cleanup. This fix will be correct functionally and shouldn't crash but may be leaking memory. There, however, is a memory leak problem somewhere but it is difficult to say where. This will be addressed in a different issue.
